{
 "title": "CPU Dashboard",
 "tags": [
  "monitoring-lab",
  "cpu"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Host CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])))",
     "legendFormat": "host cpu used %"
    }
   ]
  },
  {
   "title": "App Container CPU (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_com_docker_compose_service=\"app\",image!=\"\"}[1m])) or sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",name=~\".*mon-app.*\",image!=\"\"}[1m]))",
     "legendFormat": "app cpu cores"
    }
   ]
  },
  {
   "title": "Synthetic CPU Spike Flag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_cpu_spike_active", "legendFormat": "cpu spike active" }
   ]
  }
 ]
}