{
 "title": "Error Rate Dashboard",
 "tags": [
  "monitoring-lab",
  "errors",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx req/s"
    }
   ]
  },
  {
   "title": "Error Percentage (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(app_http_requests_total{status=~\"5..\",route!=\"/metrics\"}[5m])) / clamp_min(sum(rate(app_http_requests_total{route!=\"/metrics\"}[5m])), 0.001)",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Log Anomaly Rate (Loki)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"app\"} |= \"ANOMALY\" [1m]))",
     "legendFormat": "anomaly logs/min"
    }
   ]
  },
  {
   "title": "Anomaly Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"app\"} |= \"ANOMALY\""
    }
   ]
  }
 ]
}