{
 "title": "Request Rate Dashboard",
 "tags": [
  "monitoring-lab",
  "requests"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{route!=\"/metrics\"}[1m]))",
     "legendFormat": "total req/s"
    }
   ]
  },
  {
   "title": "Request Rate by Route / Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, status) (rate(app_http_requests_total{route!=\"/metrics\"}[1m]))",
     "legendFormat": "{{route}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP P95 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_http_request_duration_seconds_bucket{route!=\"/metrics\"}[5m]))) * 1000",
     "legendFormat": "p95 http latency"
    }
   ]
  },
  {
   "title": "DB P95 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_db_query_latency_seconds_bucket[5m]))) * 1000",
     "legendFormat": "p95 db latency"
    }
   ]
  }
 ]
}