apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-prod
  namespace: argocd
spec:
  project: platform-lab
  source:
    repoURL: https://github.com/parrsi01/DevOps.git
    targetRevision: main
    path: projects/gitops-workflow-lab/apps/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
